# Generated by Django 3.1.1 on 2020-10-01 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='availability_status',
            field=models.BooleanField(default=True, verbose_name='Наличие на складе'),
        ),
    ]
