# Generated by Django 3.1.1 on 2020-10-02 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20201002_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='product.subcategory', verbose_name='Подкатегория товара'),
        ),
        migrations.AlterField(
            model_name='saleproduct',
            name='new_price',
            field=models.DecimalField(db_index=True, decimal_places=0, max_digits=10, verbose_name='Новая цена'),
        ),
        migrations.AlterField(
            model_name='saleproduct',
            name='old_price',
            field=models.DecimalField(db_index=True, decimal_places=0, max_digits=10, verbose_name='Старая цена'),
        ),
    ]
